server.port=8085
spring.application.name=siza-server
server.servlet.context-path=/siza-server
spring.datasource.url=jdbc:postgresql://3.128.255.103:5432/siza_db
spring.jpa.properties.hibernate.default_schema=siza_db
spring.datasource.username=admin
spring.datasource.password=Siza@2026

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=1

logging.file.name=/home/ubuntu/logs/siza-server/siza-server.log